[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "cd ../../shared && npm install && npm run build",
  "cd ../../services/auth-service && npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod" 